# Generated by Django 5.2.13 on 2026-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='server',
            name='cadvisor_port',
            field=models.IntegerField(default=8080),
        ),
        migrations.AddField(
            model_name='server',
            name='has_containers',
            field=models.BooleanField(default=False, help_text='If True, cAdvisor will also be installed for container monitoring'),
        ),
        migrations.AddField(
            model_name='server',
            name='node_exporter_port',
            field=models.IntegerField(default=9100),
        ),
        migrations.AddField(
            model_name='server',
            name='setup_logs',
            field=models.TextField(blank=True, default='', help_text='Logs from the setup process'),
        ),
        migrations.AddField(
            model_name='server',
            name='setup_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Setup Running'), ('success', 'Setup Successful'), ('failed', 'Setup Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_active',
            field=models.BooleanField(default=False, help_text='True if monitoring agents are running'),
        ),
    ]
